#!/bin/bash
m="\033[1;31m"
p="\033[1;37m"
k="\033[1;33m"
h="\033[1;32m"
c="\033[1;36m"
grs="\033[4m"
pe="\033[00m"
ce="\033[0;36m"

echo -e "${c}[+] ${pe}Downloading packagaes metasploit-framework"
echo -e "${c}[+] ${pe}Please wait.."
echo -e "${c}[+] ${pe}Installing in termux"
pkg install unstable-repo metasploit -y
echo -e "${c}[+] ${pe}Installing Successfully run '${h}msfconsole${pe}'"
exit


